cloud_sources:
  - name: tilt_scan_cloud_filtered
    # take every nth frame (1 is no discards)
    frame_subsample: 1
    # take every nth point from the frames you do process
    point_subsample: 1 
    sensor_frame: kinect_depth
    dynamic_publish: false
    static_publish: true
    dynamic_until_static_publish: true
