## This file should be loaded under <robot description>_collision
#
# By default, the collision environment does not check for self collisions
# between any robot links, so all necessary collision checks have to 
# be explicitly enabled here.
#
# The collision groups specified here are defined in planning_groups.yaml.
#
# also see http://www.ros.org/wiki/planning_environment/YAML%20configuration

default_collision_operations:
# check for collisions between body and arm, body and end effector, arm and 
# end effector;
  - object1: robot_body
    object2: arm
    operation: enable

  - object1: robot_body
    object2: end_effector
    operation: enable

  - object1: end_effector
    object2: arm
    operation: enable

# disable collision checks between adjacent links in separate planning groups
  - object1: katana_motor1_pan_link
    object2: robot_body
    operation: disable

  - object1: katana_motor4_lift_link
    object2: end_effector
    operation: disable

# disable collision checks between links that cannot physically collide
# (to speed up computation)
  - object1: katana_motor1_pan_link
    object2: robot_body
    operation: disable

