## This file should be loaded under <robot description>_planning

groups:
  - name: robot_body
    links:
      katana_internal_controlbox_link
      katana_base_link
## TODO: add all other links and joints of the robot body here (chassis, ...)

  - name: arm
    joints:
      katana_motor1_pan_joint
      katana_motor2_lift_joint
      katana_motor3_lift_joint
      katana_motor4_lift_joint
      katana_motor5_wrist_roll_joint
    links:
      katana_motor1_pan_link
      katana_motor2_lift_link
      katana_motor3_lift_link
      katana_motor4_lift_link
#      katana_gripper_tool_frame

  - name: end_effector
    links: 
      katana_motor5_wrist_roll_link
      katana_gripper_link
      katana_l_finger_link
      katana_r_finger_link

## katana_motor5_wrist_roll_link is included in end_effector group so that
## self-collisions with the arm group are checked (it can physically collide 
## with katana_motor1_pan_link).
##
## all links and joints from the URDF are listed here, except for
## - the two fixed joints
## - the link and joint required by the KNI inverse kinematics (katana_base_frame_link)
## - the gripper joints (katana_r_finger_joint, katana_l_finger_joint), because they should not
##   be planned for by the motion planner, but rather be used by the grasping pipeline

